#!/bin/bash
#                                                                     2021-11-20
#    FirstBoot time installation of raspi-manager
#
#    You get bugy/script-server running on your raspberry
#
################################################################################
#                                                                         avviso
#*************************** Versione di prova start
log "Start manager-boot"

exit
#*************************** Versione di prova end

echo
echo "============================================================ PC GOTHINGS"
echo
echo "      GOTHINGS boot loader for PC Manager"
echo
echo "============================================================ version 1.00"
echo
#
################################################################################
#                                          download latest manager da repository
#
wget -O ${HOME}/managerdirs.tar.gz https://github.com/fpirri/gothings-raspi-manager/raw/main/managerdirs.tar.gz
#
################################################################################
#                                                             expand in dockrepo
#
sudo tar xpf "${HOME}/managerdirs.tar.gz" -C "${HOME}"
#
#
################################################################################
#                                                                installa sul PC
#
./dockrepo/raspi-manager/install_raspi_manager
#
################################################################################
#                                                                Avvisa l'utente
#
echo
echo "No errors?"
echo
echo "Congratulations! You have installed your PC Manager"
echo
echo "Open a browser in this PC and go to the site:"
echo "  localhost:5000"
echo
echo "You may like to try the script 'Ping your raspi'"
echo
echo "Please have a look at the documentation at 'www.gothings.org'"
echo
