#!/bin/bash
#                                                                     2021-11-20
#    FirstBoot time installation of raspi-manager
#
#    You get bugy/script-server running on your raspberry
#
#
################################################################################
#                                                               log script start
LogFile="$HOME/firstboot.sh.log"
echo "`date` manager-boot start" >> "${LogFile}"
#
################################################################################
#                                                                 Funzioni utili
#------------
log() {
#  $1   stringa da scrivere su firstboot.sh.log
  echo $1 >> "${LogFile}"
}
#------------
errorstop() {
#  $1   codice di errore
#  $2   stringa di errore
#  $3   label chiamante (per sapere dove ...)
  if [ $1 -gt 0 ]
  then
    echo "$3 | error $1 - $2" >> "$HOME/firstboot.sh.log"
    echo "`date` firstboot.sh end" >> "$HOME/firstboot.sh.log"
    exit
  else
    echo "$3 | passed" >> "$HOME/firstboot.sh.log"
  fi
}
#
#---------
setdir() {
#  $1  verifica esistenza dir
#        <-- crea dir se non esiste
  local Result
  if [ ! -d "$1" ]; then
    mkdir "$1"
    Result=$?
    errorstop ${Result} "set dir $1 non riuscito"  "set dir $1"
  fi
}
#
################################################################################
#                                                                         avviso
log "Start manager-boot"
#
################################################################################
#                                          download latest manager da repository
#
wget -O ${HOME}/managerdirs.tar.gz https://github.com/fpirri/gothings-raspi-manager/raw/main/managerdirs.tar.gz
#
#
################################################################################
#                                                             expand in dockrepo
#
tar xpf "${HOME}/managerdirs.tar.gz" -C "${HOME}"
Result=$?
errorstop ${Result} "expand managerdirs.tar.gz error"  "Get managerdirs.tar.gz"
#
################################################################################
#                                                               Lancia il server
cd /dockrepo/raspi-manager
echo "provo a lanciare lo script-server ..."
python3 launcher.py

exit
#*************************** Versione di prova end


################################################################################
#                                                                installa sul PC
#
./dockrepo/raspi-manager/install_raspi_manager
Result=$?
errorstop ${Result} "install raspi-manager error"  "Install raspi-manager"
#
################################################################################
#                                                                Avvisa l'utente
#
echo
echo "No errors?"
echo
echo "Congratulations! You have installed your PC Manager"
echo
echo "Open a browser in this PC and go to the site:"
echo "  localhost:5000"
echo
echo "You may like to try the script 'Ping your raspi'"
echo
echo "Please have a look at the documentation at 'www.gothings.org'"
echo
